services:
  mysql:
    image: mysql:8.0
    container_name: airlines_mysql
    command: 
      --default-authentication-plugin=mysql_native_password 
      --mysqlx=ON 
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 1162005
      MYSQL_DATABASE: airlines_db
      MYSQL_USER: cuong116
      MYSQL_PASSWORD: 1162005
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  mysql_data:
