services:
  mysql:
    image: mysql:8.0
    container_name: airlines_mysql
    command: --default-authentication-plugin=mysql_native_password --mysqlx=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-phucHoang133205}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-airlines_db}
      MYSQL_USER: ${MYSQL_USER:-nphoang}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-phucHoang133205}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"   # Classic MySQL protocol
      - "33060:33060" # X Protocol port
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  mysql_data: