services:
  mysql:
    image: mysql:8.0
    container_name: airlines_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-phucHoang133205}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-airlines_db}
      MYSQL_USER: ${MYSQL_USER:-nphoang}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-phucHoang133205}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306" # Ánh xạ port 3306 của container ra máy host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  mysql_data: